const video=document.getElementById("video"),captureCanvas=document.getElementById("captureCanvas"),countdown=document.getElementById("countdown"),cameraMessage=document.getElementById("cameraMessage");
const startCameraButton=document.getElementById("startCamera"),startSessionButton=document.getElementById("startSession"),finalizeButton=document.getElementById("finalizeButton"),applyFilterButton=document.getElementById("applyFilter"),saveButton=document.getElementById("saveButton"),newSessionButton=document.getElementById("newSession");
const progressNumber=document.getElementById("progressNumber"),progressBar=document.getElementById("progressBar"),progressRing=document.getElementById("progressRing"),photoCounter=document.getElementById("photoCounter"),readyText=document.getElementById("readyText"),captureHint=document.getElementById("captureHint"),status=document.getElementById("status");
const stylePanel=document.getElementById("stylePanel"),finalPanel=document.getElementById("finalPanel"),selectedBadge=document.getElementById("selectedBadge"),finalStyle=document.getElementById("finalStyle"),finalStyleName=document.getElementById("finalStyleName"),finalDate=document.getElementById("finalDate"),finalCanvas=document.getElementById("finalCanvas");
const steps=[document.getElementById("step1"),document.getElementById("step2"),document.getElementById("step3")],photoCards=[document.getElementById("photoCard1"),document.getElementById("photoCard2"),document.getElementById("photoCard3")];
let stream=null,capturedPhotos=[],selectedFilter="original",sessionRunning=false;

const names={original:"Original",futuristic:"Futuristic",vector:"Vector Art",collage:"Collage Art",retro:"Retro",cyberpunk:"Cyberpunk",popart:"Pop Art",glass:"Glass Morphism",clay:"Clay Style",pixel:"Pixel Art",y2k:"Y2K",bohemian:"Bohemian",victorian:"Victorian",graffiti:"Graffiti"};

const cssFilters={original:"none",futuristic:"contrast(1.2) saturate(1.55) brightness(1.05) hue-rotate(12deg)",vector:"saturate(1.8) contrast(1.5)",collage:"saturate(1.2) contrast(1.1)",retro:"sepia(.55) saturate(1.2) contrast(.92)",cyberpunk:"saturate(2) contrast(1.45) hue-rotate(25deg)",popart:"saturate(2.1) contrast(1.55)",glass:"brightness(1.12) saturate(.85)",clay:"saturate(.65) brightness(1.12) contrast(.88)",pixel:"saturate(1.55) contrast(1.25)",y2k:"saturate(1.8) brightness(1.1) hue-rotate(10deg)",bohemian:"sepia(.35) saturate(.9) brightness(1.05)",victorian:"sepia(.35) contrast(1.18) brightness(.9)",graffiti:"saturate(2.1) contrast(1.5) hue-rotate(-10deg)"};

function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function setStatus(x){status.textContent=x}
function updateSteps(n){steps.forEach(s=>s.classList.remove("active","done"));for(let i=0;i<n-1;i++)steps[i].classList.add("done");steps[n-1].classList.add("active")}
function updateProgress(){let n=capturedPhotos.length;progressNumber.textContent=n;photoCounter.textContent=`${n} / 3`;progressBar.style.width=`${n/3*100}%`;progressRing.style.background=`conic-gradient(#8b5cf6 ${n/3*360}deg,#263249 0deg)`;if(n===3){finalizeButton.disabled=false;readyText.textContent="All photos captured";captureHint.textContent="Finalize your photos to choose a style."}}
async function startCamera(){try{if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;cameraMessage.classList.add("hidden");startSessionButton.disabled=false;startCameraButton.textContent="✓ Camera Connected";readyText.textContent="Ready to capture";setStatus("Camera connected.")}catch(e){console.error(e);setStatus("Camera access failed. Allow permission and try again.")}}
function renderCaptured(){photoCards.forEach((c,i)=>{c.innerHTML=`<span>0${i+1}</span>`;if(capturedPhotos[i]){let img=document.createElement("img");img.src=capturedPhotos[i];c.appendChild(img)}else{let e=document.createElement("em");e.textContent="WAITING";c.appendChild(e)}})}
function capturePhoto(){if(!video.videoWidth)return;captureCanvas.width=video.videoWidth;captureCanvas.height=video.videoHeight;let c=captureCanvas.getContext("2d");c.save();c.translate(captureCanvas.width,0);c.scale(-1,1);c.drawImage(video,0,0);c.restore();capturedPhotos.push(captureCanvas.toDataURL("image/jpeg",.94));renderCaptured();updateProgress()}
async function takeCountdown(){for(let n=3;n>0;n--){countdown.classList.remove("hidden");countdown.textContent=n;countdown.style.animation="none";void countdown.offsetWidth;countdown.style.animation="countdownPop .65s ease";await wait(1000)}countdown.textContent="📸";await wait(220);countdown.classList.add("hidden");capturePhoto()}
async function startSession(){if(!stream){await startCamera();if(!stream)return}if(sessionRunning)return;capturedPhotos=[];sessionRunning=true;renderCaptured();updateProgress();startSessionButton.disabled=true;startCameraButton.disabled=true;finalizeButton.disabled=true;updateSteps(1);for(let i=0;i<3;i++){readyText.textContent=`Photo ${i+1} of 3 — get ready!`;await wait(600);await takeCountdown();if(i<2)await wait(700)}sessionRunning=false;startCameraButton.disabled=false;readyText.textContent="Session complete";setStatus("All 3 photos captured.")}
function makePreviews(){document.querySelectorAll(".filter-card").forEach(card=>{let box=card.querySelector(".filter-preview");box.innerHTML="";capturedPhotos.forEach(src=>{let img=document.createElement("img");img.src=src;img.style.filter=cssFilters[card.dataset.filter];if(card.dataset.filter==="pixel")img.style.imageRendering="pixelated";box.appendChild(img)})})}
function selectFilter(f){selectedFilter=f;document.querySelectorAll(".filter-card").forEach(c=>c.classList.toggle("active",c.dataset.filter===f));selectedBadge.textContent=names[f].toUpperCase();applyFilterButton.disabled=false;setStatus(`${names[f]} selected.`)}
function finalizePhotos(){if(capturedPhotos.length!==3)return;makePreviews();updateSteps(2);stylePanel.scrollIntoView({behavior:"smooth"});setStatus("Choose one of the 14 visual styles.")}
function clamp(v){return Math.max(0,Math.min(255,v))}
function processPixels(ctx,w,h,mode){let im=ctx.getImageData(0,0,w,h),d=im.data;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],gray=r*.299+g*.587+b*.114;
if(mode==="vector"){let q=5;r=Math.round(r/255*(q-1))*255/(q-1);g=Math.round(g/255*(q-1))*255/(q-1);b=Math.round(b/255*(q-1))*255/(q-1)}
if(mode==="popart"){if(gray<70){r=25;g=10;b=75}else if(gray<145){r=255;g=45;b=115}else if(gray<205){r=255;g=205;b=40}else{r=255;g=245;b=205}}
if(mode==="retro"){let R=.393*r+.769*g+.189*b,G=.349*r+.686*g+.168*b,B=.272*r+.534*g+.131*b;r=R*.9;g=G*.9;b=B*.9}
if(mode==="clay"){r=r*.65+gray*.35;g=g*.65+gray*.35;b=b*.65+gray*.35;r*=1.08;g*=1.01}
if(mode==="pixel"){let q=32;r=Math.round(r/q)*q;g=Math.round(g/q)*q;b=Math.round(b/q)*q}
if(mode==="cyberpunk"){let cy=b*.65+g*.25,ma=r*.72+b*.18;r=ma*1.15;g=cy*.72;b=cy*1.15+ma*.18}
if(mode==="y2k"){r=r*1.12+b*.08;g=g*.98+8;b=b*1.16+10}
if(mode==="bohemian"){r=r*1.08+12;g=g+4;b=b*.88}
if(mode==="victorian"){r=gray*.98+r*.12;g=gray*.93+g*.08;b=gray*.82+b*.04}
if(mode==="graffiti"){r=r*1.25+15;g=g*.88+4;b=b*1.2+10}
d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(b)}ctx.putImageData(im,0,0)}
function neon(ctx,x,y,w,h){ctx.save();ctx.globalAlpha=.7;ctx.lineWidth=2;for(let i=0;i<6;i++){ctx.strokeStyle=i%2?"#ff4bd4":"#35e6ff";ctx.beginPath();ctx.moveTo(x,y+35+i*65);ctx.lineTo(x+w,y+5+i*65);ctx.stroke()}ctx.restore()}
function dots(ctx,x,y,w,h){ctx.save();ctx.globalAlpha=.2;ctx.fillStyle="#111";for(let yy=y;yy<y+h;yy+=10)for(let xx=x;xx<x+w;xx+=10){ctx.beginPath();ctx.arc(xx,yy,1.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function graffiti(ctx,x,y,w,h){ctx.save();ctx.globalAlpha=.2;["#ff2cc0","#27e7ff","#ffe23c","#8655ff"].forEach((c,i)=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(x+w*(.15+.23*i),y+h*(.25+.13*(i%2)),55+10*i,0,Math.PI*2);ctx.fill()});ctx.restore()}
function decor(ctx,style,x,y,w,h){if(style==="futuristic"||style==="cyberpunk")neon(ctx,x,y,w,h);if(style==="popart")dots(ctx,x,y,w,h);if(style==="graffiti")graffiti(ctx,x,y,w,h);if(style==="glass"){ctx.fillStyle="rgba(255,255,255,.1)";ctx.fillRect(x,y,w,h);ctx.strokeStyle="rgba(255,255,255,.5)";ctx.lineWidth=3;ctx.strokeRect(x+10,y+10,w-20,h-20)}if(style==="collage"){ctx.fillStyle="#f4dfbd";ctx.fillRect(x+18,y+18,130,35);ctx.fillStyle="#151827";ctx.fillRect(x+w-150,y+h-52,132,34)}if(style==="pixel"){ctx.globalAlpha=.13;ctx.strokeStyle="#fff";for(let xx=x;xx<x+w;xx+=10){ctx.beginPath();ctx.moveTo(xx,y);ctx.lineTo(xx,y+h);ctx.stroke()}for(let yy=y;yy<y+h;yy+=10){ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+w,yy);ctx.stroke()}ctx.globalAlpha=1}}
async function image(src){return new Promise((res,rej)=>{let i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=src})}
async function drawStyled(ctx,img,style,x,y,w,h){ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,14);ctx.clip();if(style==="pixel"){let t=document.createElement("canvas"),tw=Math.floor(w/7),th=Math.floor(h/7);t.width=tw;t.height=th;t.getContext("2d").drawImage(img,0,0,tw,th);ctx.imageSmoothingEnabled=false;ctx.drawImage(t,0,0,tw,th,x,y,w,h);ctx.imageSmoothingEnabled=true;processPixels(ctx,w,h,"pixel")}else{ctx.filter=cssFilters[style]||"none";ctx.drawImage(img,x,y,w,h);ctx.filter="none";if(["vector","popart","retro","cyberpunk","clay","y2k","bohemian","victorian","graffiti"].includes(style))processPixels(ctx,w,h,style)}decor(ctx,style,x,y,w,h);ctx.restore()}
async function createTemplate(){let W=760,PW=650,PH=470,S=55,G=18,H=125,F=100;finalCanvas.width=W;finalCanvas.height=H+PH*3+G*2+F;let c=finalCanvas.getContext("2d");c.fillStyle=["retro","bohemian","victorian"].includes(selectedFilter)?"#eee2c8":selectedFilter==="popart"?"#fff0a5":selectedFilter==="clay"?"#e7d8d0":"#080d16";c.fillRect(0,0,W,finalCanvas.height);c.textAlign="center";c.fillStyle=["futuristic","cyberpunk","y2k"].includes(selectedFilter)?"#7cecff":["retro","bohemian","victorian"].includes(selectedFilter)?"#4e3a2d":"#f4f6ff";c.font="700 32px Arial";c.fillText("JEM'S PHOTOBOOTH",W/2,55);c.font="600 12px Arial";c.fillStyle="#7f8ba1";c.fillText(`${names[selectedFilter].toUpperCase()} • 03 MOMENTS`,W/2,82);
for(let i=0;i<3;i++){let img=await image(capturedPhotos[i]),y=H+i*(PH+G);await drawStyled(c,img,selectedFilter,S,y,PW,PH);c.fillStyle="#05080dbb";c.beginPath();c.arc(S+28,y+28,17,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.font="700 12px Arial";c.fillText(String(i+1).padStart(2,"0"),S+28,y+32)}
c.textAlign="left";c.fillStyle=["futuristic","cyberpunk","y2k"].includes(selectedFilter)?"#6de9ff":"#9f86ff";c.font="700 20px Arial";c.fillText(names[selectedFilter],S,finalCanvas.height-48);c.strokeStyle=["futuristic","cyberpunk","y2k"].includes(selectedFilter)?"#35e6ff":"#8b5cf6";c.lineWidth=2;c.beginPath();c.moveTo(S,finalCanvas.height-70);c.lineTo(W-S,finalCanvas.height-70);c.stroke();c.textAlign="right";c.fillStyle="#78859b";c.font="11px Arial";c.fillText(new Date().toLocaleDateString(),W-S,finalCanvas.height-48)}
async function applySelectedFilter(){if(capturedPhotos.length!==3)return;applyFilterButton.disabled=true;setStatus(`Rendering ${names[selectedFilter]}...`);try{await createTemplate();finalStyle.textContent=names[selectedFilter].toUpperCase();finalStyleName.textContent=names[selectedFilter];finalDate.textContent=new Date().toLocaleDateString();finalPanel.classList.remove("hidden");updateSteps(3);finalPanel.scrollIntoView({behavior:"smooth"});setStatus("✓ Your styled photostrip is ready.")}catch(e){console.error(e);setStatus("Could not render this style.")}finally{applyFilterButton.disabled=false}}
async function savePhoto(){try{saveButton.disabled=true;setStatus("Saving...");let r=await fetch("/api/photos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:finalCanvas.toDataURL("image/jpeg",.94),filter:selectedFilter,photoCount:3})}),j=await r.json();if(!r.ok||!j.success)throw Error(j.message);setStatus("✓ Photo saved successfully.")}catch(e){console.error(e);setStatus("Save failed. Check the Node.js server.")}finally{saveButton.disabled=false}}
function resetSession(){capturedPhotos=[];selectedFilter="original";renderCaptured();updateProgress();finalPanel.classList.add("hidden");applyFilterButton.disabled=true;finalizeButton.disabled=true;startSessionButton.disabled=!stream;selectedBadge.textContent="ORIGINAL";updateSteps(1);setStatus("New session ready.")}
function renderCaptured(){photoCards.forEach((c,i)=>{c.innerHTML=`<span>0${i+1}</span>`;if(capturedPhotos[i]){let img=document.createElement("img");img.src=capturedPhotos[i];c.appendChild(img)}else{let e=document.createElement("em");e.textContent="WAITING";c.appendChild(e)}})}
startCameraButton.onclick=startCamera;startSessionButton.onclick=startSession;finalizeButton.onclick=finalizePhotos;applyFilterButton.onclick=applySelectedFilter;saveButton.onclick=savePhoto;newSessionButton.onclick=resetSession;
document.querySelectorAll(".filter-card").forEach(c=>c.onclick=()=>selectFilter(c.dataset.filter));updateProgress();renderCaptured();
